# Default values for helmdemo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

front:
  imagename: frontend
  podimage: svinitha06/clientnew:1.0
  podname: myapp-front
  podlabel: frontpod
  deploymentname: myapp-frontdeployment
  deploymentlabel: frontdeployment
  replicacount: 2
  ingressname: ingress-front
  hostname: bookingfront.com
  servicename: myapp-frontservice
  serviceport: 3000
  servicelabel: frontservice
  servicetype: NodePort
  targetport: 3000
  nodeport: 30008

back:
  imagename: backend
  podimage: svinitha06/servernew:1.0
  podname: myapp-back
  podlabel: backpod
  deploymentname: myapp-backdeployment
  deploymentlabel: backdeployment
  replicacount: 2
  ingressname: ingress-back
  hostname: bookingback.com
  servicename: myapp-backservice
  serviceport: 5000
  servicelabel: backservice
  servicetype: NodePort
  targetport: 5000
  nodeport: 30009


replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
