apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.back.ingressname }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.back.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.back.servicename }}
              servicePort: {{ .Values.back.serviceport }}