apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.front.ingressname }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: {{ .Values.front.hostname }}
      http:
        paths:
          - backend:
              serviceName: {{ .Values.front.servicename }}
              servicePort: {{ .Values.front.serviceport }}