apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.front.servicename }}
  labels:
    app: {{ .Values.front.servicelabel}}
spec:
  type: {{ .Values.front.servicetype }}
  ports:
    - targetPort: {{ .Values.front.targetport}}
      port: {{ .Values.front.serviceport }}
      nodePort: {{ .Values.front.nodeport }}
  selector:
    app: {{ .Values.front.podlabel }}
    